/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedAddMoneyRouteImport } from './routes/_authenticated/add-money'
import { Route as AuthenticatedBudgetsRouteImport } from './routes/_authenticated/budgets'
import { Route as AuthenticatedDepositRouteImport } from './routes/_authenticated/deposit'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedPayRouteImport } from './routes/_authenticated/pay'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedTransferRouteImport } from './routes/_authenticated/transfer'
import { Route as AuthenticatedAccountsIndexRouteImport } from './routes/_authenticated/accounts.index'
import { Route as AuthenticatedAccountsAccountIdRouteImport } from './routes/_authenticated/accounts.$accountId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAddMoneyRoute = AuthenticatedAddMoneyRouteImport.update({
  id: '/add-money',
  path: '/add-money',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBudgetsRoute = AuthenticatedBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepositRoute = AuthenticatedDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayRoute = AuthenticatedPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransferRoute = AuthenticatedTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsIndexRoute =
  AuthenticatedAccountsIndexRouteImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsAccountIdRoute =
  AuthenticatedAccountsAccountIdRouteImport.update({
    id: '/accounts/$accountId',
    path: '/accounts/$accountId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/add-money': typeof AuthenticatedAddMoneyRoute
  '/budgets': typeof AuthenticatedBudgetsRoute
  '/deposit': typeof AuthenticatedDepositRoute
  '/home': typeof AuthenticatedHomeRoute
  '/pay': typeof AuthenticatedPayRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/transfer': typeof AuthenticatedTransferRoute
  '/accounts/$accountId': typeof AuthenticatedAccountsAccountIdRoute
  '/accounts/': typeof AuthenticatedAccountsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/add-money': typeof AuthenticatedAddMoneyRoute
  '/budgets': typeof AuthenticatedBudgetsRoute
  '/deposit': typeof AuthenticatedDepositRoute
  '/home': typeof AuthenticatedHomeRoute
  '/pay': typeof AuthenticatedPayRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/transfer': typeof AuthenticatedTransferRoute
  '/accounts/$accountId': typeof AuthenticatedAccountsAccountIdRoute
  '/accounts': typeof AuthenticatedAccountsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/add-money': typeof AuthenticatedAddMoneyRoute
  '/_authenticated/budgets': typeof AuthenticatedBudgetsRoute
  '/_authenticated/deposit': typeof AuthenticatedDepositRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/pay': typeof AuthenticatedPayRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/transfer': typeof AuthenticatedTransferRoute
  '/_authenticated/accounts/$accountId': typeof AuthenticatedAccountsAccountIdRoute
  '/_authenticated/accounts/': typeof AuthenticatedAccountsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/add-money'
    | '/budgets'
    | '/deposit'
    | '/home'
    | '/pay'
    | '/profile'
    | '/transfer'
    | '/accounts/$accountId'
    | '/accounts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/add-money'
    | '/budgets'
    | '/deposit'
    | '/home'
    | '/pay'
    | '/profile'
    | '/transfer'
    | '/accounts/$accountId'
    | '/accounts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/add-money'
    | '/_authenticated/budgets'
    | '/_authenticated/deposit'
    | '/_authenticated/home'
    | '/_authenticated/pay'
    | '/_authenticated/profile'
    | '/_authenticated/transfer'
    | '/_authenticated/accounts/$accountId'
    | '/_authenticated/accounts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/add-money': {
      id: '/_authenticated/add-money'
      path: '/add-money'
      fullPath: '/add-money'
      preLoaderRoute: typeof AuthenticatedAddMoneyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budgets': {
      id: '/_authenticated/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AuthenticatedBudgetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deposit': {
      id: '/_authenticated/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof AuthenticatedDepositRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pay': {
      id: '/_authenticated/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof AuthenticatedPayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transfer': {
      id: '/_authenticated/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof AuthenticatedTransferRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/': {
      id: '/_authenticated/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthenticatedAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/$accountId': {
      id: '/_authenticated/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AuthenticatedAccountsAccountIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAddMoneyRoute: typeof AuthenticatedAddMoneyRoute
  AuthenticatedBudgetsRoute: typeof AuthenticatedBudgetsRoute
  AuthenticatedDepositRoute: typeof AuthenticatedDepositRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedPayRoute: typeof AuthenticatedPayRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTransferRoute: typeof AuthenticatedTransferRoute
  AuthenticatedAccountsAccountIdRoute: typeof AuthenticatedAccountsAccountIdRoute
  AuthenticatedAccountsIndexRoute: typeof AuthenticatedAccountsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAddMoneyRoute: AuthenticatedAddMoneyRoute,
  AuthenticatedBudgetsRoute: AuthenticatedBudgetsRoute,
  AuthenticatedDepositRoute: AuthenticatedDepositRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedPayRoute: AuthenticatedPayRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTransferRoute: AuthenticatedTransferRoute,
  AuthenticatedAccountsAccountIdRoute: AuthenticatedAccountsAccountIdRoute,
  AuthenticatedAccountsIndexRoute: AuthenticatedAccountsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
